import "@/app/shared/styles/globals.css";
import { PropsWithChildren } from "react";
import HeaderProvider from "@/app/shared/provider/headerProvider";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Docthru",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body className={``}>
        <HeaderProvider />
        {children}
      </body>
    </html>
  );
}
